[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Monad Configuration
# TODO: Add RPC URL and Chain ID
eth-rpc-url="https://devnet1.monad.xyz/rpc/8XQAiNSsPCrIdVttyeFLC6StgvRNTdf"
chain_id = 41454


# TODO: Add Explorer URL and Chain ID
[etherscan]
monadDevnet = { key = "Monad", url = "https://brightstar-884.devnet1.monad.xyz/", chain = 41454 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
